# Generated by Django 4.2 on 2024-05-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('privado', models.BooleanField(choices=[(True, 'Privado'), (False, 'Público')])),
            ],
        ),
    ]
