# Generated by Django 4.2 on 2024-05-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id_producto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
