# Generated by Django 4.2 on 2024-05-02 22:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_productos_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='id_producto',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
