# Generated by Django 4.2 on 2024-05-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_productos_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='privado',
            field=models.BooleanField(choices=[(True, 'Privado'), (False, 'Público')], default=False),
        ),
    ]
