# Generated by Django 4.2 on 2024-05-03 00:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_productos_privado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('ContactoId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('NombreCliente', models.CharField(max_length=64, null=True)),
                ('EmailCliente', models.EmailField(max_length=50, null=True)),
                ('Mensaje', models.TextField()),
            ],
        ),
    ]
