# Generated by Django 4.2 on 2024-05-07 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_productos_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='liviano',
            field=models.BooleanField(choices=[(True, 'Sin azúcar'), (False, 'Tradicional')], default=False),
        ),
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
